name: sha
description: A new Flutter project.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  kt_dart: ^1.1.0
  tuple: ^2.0.2
  url_launcher: ^6.1.12
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  google_sign_in:
  flutter_signin_button:
  mobile_scanner: ^3.3.0
  logger: ^2.0.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.2.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  sliver_tools: ^0.2.12
  equatable: ^2.0.5
  shared_preferences:
  hive:
  hive_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/images/connected_world.svg
    - assets/images/time_management.svg
    - assets/images/voice_assistant.svg